### ISSUE TITLE
resize by max value

### ISSUE THREAD

**Issue by protokovich** [muak/Xamarin.Plugin.ImageEdit#2]
suggest adding the function, which resize by one(max) value: 

```
public static class SizeHelper
    {
        public static Size Resize(this Size oldSize, int maxValue)
        {
            var aspect = oldSize.Width / oldSize.Height;

            int newW;
            int newH;

            if (aspect > 1) // landscape
            {
                newW = (int)Math.Min(oldSize.Width, maxValue);
                newH = (int)Math.Truncate(newW / aspect + 0.5);
            }
            else
            {
                newH = (int)Math.Min(oldSize.Height, maxValue);
                newW = (int)Math.Truncate(newH * aspect + 0.5);
            }
            return new Size(newW, newH);
        }
    }
```
example:
all images in my database has max size(width and height) = 1500
i have image 3000x2000. i need 1500:1000
i have 2000x3000. i need 1000:1500

Size newSize = origSize.Resize(1500);
..... Resize(newSize.Width, newSize.Height);

Such a function can be useful :)

**Comment by muak** [comment]
@protokovich 
Thank you for this nice suggestion too.
I'm going to consider how to incorporate this method to method chaining.
