### ISSUE TITLE
add please function, which return 'native' Image object

### ISSUE THREAD

**Issue by protokovich** [muak/Xamarin.Plugin.ImageEdit#3]
interface...
object GetNativeImage();

// android
public object GetNativeObject(){
  return _image;
}

// ios
public object GetNativeObject(){
  return _image;
}

i want use my own manipulations with native image object, together with your functions

**Comment by muak** [comment]
@protokovich 
How do you want to use native object?
In case pcl project, it cannot manipulate native object even if recieve it.
Are you going to use in native project?

**Comment by protokovich** [comment]
i want use in native projects

**Comment by muak** [comment]
@protokovich 
I see. I'm going to consider it.
