### ISSUE TITLE
iOSでのToJpegの品質値範囲

### ISSUE THREAD

**Issue by jungoross** [muak/Xamarin.Plugin.ImageEdit#6]
日本語で失礼します。便利なプラグインをありがとうございます。

iOSでのToJpegですが、UIImage.AsJPEGのcompressionQualityは0～1.0とあります。デフォルト値が80のため、そのままだと容量が非常に大きくなってします。Androidのほうは調べていませんが、0-1.0と0-100で値の範囲が違うのではないでしょうか。

https://developer.xamarin.com/api/member/MonoTouch.UIKit.UIImage.AsJPEG/p/System.Single/

**Comment by muak** [comment]
@jungoross 
ご指摘ありがとうございます。
完全に間違っていました。ご迷惑おかけしました。
Androidの方は調べて見たところ0-100で大丈夫みたいです。
iOS側はすぐに直します！

**Comment by muak** [comment]
@jungoross 
0.1.0 で修正対応しました。

**Comment by jungoross** [comment]
ご対応ありがとうございました。
