### ISSUE TITLE
Is it possible to get pixel color based on X, Y position?

### ISSUE THREAD

**Issue by Jbonavita** [muak/Xamarin.Plugin.ImageEdit#8]
I have a case where I need to get the pixel color the user clicked on. Is it possible to do that?

Thanks!

**Comment by muak** [comment]
@Jbonavita 
Though I don't try whether it works in reality, for example, how about the following code?

```csharp
var pixels = image.ToArgbPixels();
var pos = y * image.Width + x;
var pixel = pixels[pos];
```

**Comment by Jbonavita** [comment]
Thanks. I haven't been able to figure out a way to call CreateImageAsync from an Image or ImageSource.
