### ISSUE TITLE
.Net Standard 2.0

### ISSUE THREAD

**Issue by Nico04** [muak/Xamarin.Plugin.ImageEdit#9]
Is it possible to target .NetStandard please ?

**Comment by muak** [comment]
@Nico04 

In case .NETStandard <= 1.6, If you write like the following in project.json, it is possible.

https://github.com/muak/Prism.Forms.SampleBase/blob/16ffaf86023943fbf95e12083b6cc5fd64bb28d8/Sample/project.json#L20

Also, I have the plan that I will make this library correspond to NETStandard.

**Comment by Nico04** [comment]
Thank you for your answer.
Actually Visual Studio allow your library to be used in .NetStandard project but leaves a warning saying package was restored and may not be fully compatible.
So it's not a real problem as the library seems to works fine this way, it's just an improvement request.
Thanks again for your work

**Comment by muak** [comment]
@Nico04 

I am glad to have worked it.
I accepted your request.

Thank you.

**Comment by Nico04** [comment]
More informations on the warning :
```
warning NU1701: Package 'Xamarin.Plugin.ImageEdit 0.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

**Comment by Nico04** [comment]
I'm glad you accepted my request, do you have any idea when will you update your package @muak ?
Thanks !

**Comment by Nico04** [comment]
@muak any update on this please ?

**Comment by muak** [comment]
@Nico04 

I'm sorry for keeping you waiting.
I can't update because I'm busy with work.
I will put this update into the practice by end of this year.

**Comment by Nico04** [comment]
Thank you for your update !
